### ISSUE TITLE
Follow screen application crashes finger slowly slid upwards

### ISSUE THREAD

**Issue by ghost** [bherbst/QuickReturnFooterSample#1]
Error Messages：

---

08-18 08:45:36.725  22681-22681/com.example.quickreturnbehavior E/InputEventReceiver﹕ Exception dispatching input event.
08-18 08:45:36.765  22681-22681/com.example.quickreturnbehavior E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.StackOverflowError
            at android.view.Choreographer.access$500(Choreographer.java:69)
            at android.view.Choreographer$CallbackQueue.addCallbackLocked(Choreographer.java:782)
            at android.view.Choreographer.postCallbackDelayedInternal(Choreographer.java:313)
            at android.view.Choreographer.postCallbackDelayed(Choreographer.java:299)
            at android.view.Choreographer.postCallback(Choreographer.java:273)
            at android.view.ViewRootImpl.scheduleConsumeBatchedInput(ViewRootImpl.java:5518)
            at android.view.ViewRootImpl.scheduleTraversals(ViewRootImpl.java:985)
            at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:915)
            at android.view.ViewGroup.invalidateChildFast(ViewGroup.java:4374)
            at android.view.View.invalidateViewProperty(View.java:10576)
            at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationUpdate(ViewPropertyAnimator.java:1030)
            at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1179)
            at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1115)
            at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1144)
            at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:510)
            at android.animation.ValueAnimator.start(ValueAnimator.java:921)
            at android.animation.ValueAnimator.start(ValueAnimator.java:931)
            at android.view.ViewPropertyAnimator.startAnimation(ViewPropertyAnimator.java:772)
            at android.view.ViewPropertyAnimator.start(ViewPropertyAnimator.java:355)
            at com.example.quickreturnbehavior.QuickReturnFooterBehavior.show(QuickReturnFooterBehavior.java:125)
            at com.example.quickreturnbehavior.QuickReturnFooterBehavior.access$000(QuickReturnFooterBehavior.java:23)
            at com.example.quickreturnbehavior.QuickReturnFooterBehavior$1.onAnimationCancel(QuickReturnFooterBehavior.java:82)
            at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationCancel(ViewPropertyAnimator.java:964)
            at android.animation.ValueAnimator.cancel(ValueAnimator.java:951)
            at android.view.ViewPropertyAnimator.animatePropertyBy(ViewPropertyAnimator.java:834)
            at android.view.ViewPropertyAnimator.animateProperty(ViewPropertyAnimator.java:790)
            at android.view.ViewPropertyAnimator.translationY(ViewPropertyAnimator.java:539)
            at com.example.quickreturnbehavior.QuickReturnFooterBehavior.show(QuickReturnFooterBehavior.java:101)
            at com.example.quickreturnbehavior.QuickReturnFooterBehavior.access$000(QuickReturnFooterBehavior.java:23)
            at com.example.quickreturnbehavior.QuickReturnFooterBehavior$1.onAnimationCancel(QuickReturnFooterBehavior.java:82)
            at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationCancel(ViewPropertyAnimator.java:964)
            at android.animation.ValueAnimator.cancel(ValueAnimator.java:951)
            at android.view.ViewPropertyAnimator.animatePropertyBy(ViewPropertyAnimator.java:834)
            at android.view.ViewPropertyAnimator.animateProperty(ViewPropertyAnimator.java:790)
            at android.view.ViewPropertyAnimator.translationY(ViewPropertyAnimator.java:539)
            at com.example.quickreturnbehavior.QuickReturnFooterBehavior.show(QuickReturnFooterBehavior.java:101)
            at com.example.quickreturnbehavior.QuickReturnFooterBehavior.access$000(QuickReturnFooterBehavior.java:23)
            at com.example.quickreturnbehavior.QuickReturnFooterBehavior$1.onAnimationCancel(QuickReturnFooterBehavior.java:82)
            at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationCancel(ViewPropertyAnimator.java:964)
            at android.animation.ValueAnimator.cancel(ValueAnimator.java:951)
            at android.view.ViewPropertyAnimator.animatePropertyBy(ViewPropertyAnimator.java:834)
            at android.view.ViewPropertyAnimator.animateProperty(ViewPropertyAnimator.java:790)
            at android.view.ViewPropertyAnimator.translationY(ViewPropertyAnimator.java:539)
            at com.example.quickreturnbehavior.QuickReturnFooterBehavior.show(QuickReturnFooterBehavior.java:101)
            at com.example.quickreturnbehavior.QuickReturnFooterBehavior.access$000(QuickReturnFooterBehavior.java:23)
            at com.example.quickreturnbehavior.QuickReturnFooterBehavior$1.onAnimationC

**Comment by IliaEremin** [comment]
+1
